export const GalleryData = [
    {
        id:1,
        titile:"car",
        image:"./images/a1.jpg"
    },
    {
        id:2,
        titile:"car",
        image:"./images/a2.jpg"
    },
    {
        id:3,
        titile:"car",
        image:"./images/a3.jpg"
    },
    {
        id:4,
        titile:"car",
        image:"./images/a4.jpg"
    },
    {
        id:5,
        titile:"bike",
        image:"./images/b1.jpg"
    },
    {
        id:6,
        titile:"bike",
        image:"./images/b2.jpg"
    },
    {
        id:7,
        titile:"cycle",
        image:"./images/c1.jpg"
    },
    {
        id:8,
        titile:"cycle",
        image:"./images/c2.jpg"
    },
]